name: unitests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # The debug job is meant for debugging CI related issues.
  debug:
    # Comment out the following line to enable.
    if: ${{ false }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint
        pip install coverage
        pip install -r requirements.txt
        sphinx-build --version
        pylint --version

        
    - name: setup
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        ./test/utils/spack_setup test
    
    # Set run_tests to run only the specific tests you need to fix.
    - name: run_tests
      run: | 
        coverage run ./test/run_tests -q -o index -o kickoff_independent
        coverage xml

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint
        pip install -r requirements.txt

    - name: setup
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
         
    - name: run_tests
      run: | 
        sudo -E su $USER -c "PATH=$PATH; ./test/run_tests -q -o style # -o debug_prints"

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint
        pip install -r requirements.txt

    - name: setup
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
         
    - name: run_tests
      run: ./test/run_tests -o 'doc*' -q

  unittests-3_5:
    runs-on: ubuntu-latest
    needs: 
        - style
        - docs

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint
        pip install coverage
        pip install -r requirements.txt
        sphinx-build --version
        pylint --version

        
    - name: setup
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        ./test/utils/spack_setup test
        
    - name: run_tests
      run: | 
        coverage run ./test/run_tests 
        coverage xml

#    - name: codecov-upload
#      uses: codecov/codecov-action@v2
#      with:
#        fail_ci_if_error: true
#        token: c1100f28-f36f-4b92-8ba5-ec907a1bfea6
 
  unittests-3_9:
    runs-on: ubuntu-latest
    needs: 
        - style
        - docs

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint
        pip install -r requirements.txt
    
    - name: setup
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        ./test/utils/spack_setup test
        
    - name: run_tests
      run: | 
        sudo -E su $USER -c "PATH=$PATH; ./test/run_tests"
